import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gaming Area</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <div className='space-y-12'>
        <div className='App bg-slate-900 mx-auto'>
          <Header />
          <main className='Feed'>
          {/* Hero */}
          <Hero />
          {/* About */}

          {/* Contact Us */}
          </main>
          <footer className={styles.footer}>
              Powered by wbLoki
          </footer>
        </div>
      </div>
    </div>
  )
}

export default Home;