import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div className='scrollbar scrollbar-track-black'>
      <Head>
        <title>Gaming Area</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
          <main className='Feed scrollbar scrollbar-track-violet-900 scrollbar-thumb-red-600'>
          {/* Hero */}
          <Hero />
          {/* About */}

          {/* Contact Us */}
          </main>
    </div>
  )
}

export default Home;